project:
  type: website
  output-dir: docs

website:
  title: "ML by RIT"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ritML
      # - icon: twitter
      #   href: https://twitter.com
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css



